version: "3.9"

services:
  backend:
    environment:
      JDBC_DATABASE_URL: ${JDBC_DATABASE_URL}
      JDBC_DATABASE_USERNAME: ${JDBC_DATABASE_USERNAME}
      JDBC_DATABASE_PASSWORD: ${JDBC_DATABASE_PASSWORD}
      OAUTH2_ISSUER_URI: ${OAUTH2_ISSUER_URI}
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS}
      LDAP_ENABLED: ${LDAP_ENABLED:-false}
      LDAP_PROVIDER_URL: ${LDAP_PROVIDER_URL}
      LDAP_SECURITY_AUTHENTICATION: ${LDAP_SECURITY_AUTHENTICATION}
      LDAP_SECURITY_PRINCIPAL: ${LDAP_SECURITY_PRINCIPAL}
      LDAP_SECURITY_CREDENTIALS: ${LDAP_SECURITY_CREDENTIALS}
      LDAP_PARAMETERS_NAME: ${LDAP_PARAMETERS_NAME}
      LDAP_PARAMETERS_NICKNAME: ${LDAP_PARAMETERS_NICKNAME}
      LDAP_PARAMETERS_RANK: ${LDAP_PARAMETERS_RANK}
      LDAP_PARAMETERS_COMPANY: ${LDAP_PARAMETERS_COMPANY}
      LDAP_FILTERS_BASE_OU: ${LDAP_FILTERS_BASE_OU}
      LDAP_FILTERS_USER_FILTER: ${LDAP_FILTERS_USER_FILTER}
      KEYCLOAK_CLAIMS_CPF: ${KEYCLOAK_CLAIMS_CPF}
      KEYCLOAK_CLAIMS_NAME: ${KEYCLOAK_CLAIMS_NAME}
      KEYCLOAK_CLAIMS_NICKNAME: ${KEYCLOAK_CLAIMS_NICKNAME}
      KEYCLOAK_CLAIMS_RANK: ${KEYCLOAK_CLAIMS_RANK}
      KEYCLOAK_CLAIMS_COMPANY: ${KEYCLOAK_CLAIMS_COMPANY}
      CONFIG_FRONTEND_URL: ${CONFIG_FRONTEND_URL}
    build:
      context: .
      dockerfile: backend.Dockerfile
    container_name: messageboards-backend
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 256M
    networks:
      messageboards:
        ipv4_address: ${IP_BACKEND:-192.168.100.3}
  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
      args:
        KEYCLOAK_URL: ${KEYCLOAK_URL}
        KEYCLOAK_REALM: ${KEYCLOAK_REALM}
        KEYCLOAK_CLIENT_ID: ${KEYCLOAK_CLIENT_ID}
        API_ENTRYPOINT: ${API_ENTRYPOINT}
        DEFAULT_DEADLINE_HOURS: ${DEFAULT_DEADLINE_HOURS}
        DEFAULT_DEADLINE_MINUTES: ${DEFAULT_DEADLINE_MINUTES}
    container_name: messageboards-frontend
    restart: unless-stopped
    depends_on:
      - backend
    deploy:
      resources:
        limits:
          memory: 128M
    networks:
      messageboards:
        ipv4_address: ${IP_FRONTEND:-192.168.100.2}

networks:
  messageboards:
    ipam:
      driver: default
      config:
        - subnet: ${SUBNET:-192.168.100.0/29}
