server:
  error:
    include-message: always

spring:
  profiles:
    include:
      - ${APP_PROFILE:production}
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: ${APP_DEBUG:false}