spring:
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${OAUTH2_ISSUER_URI}

logging:
  level:
    com:
      suchorski: ${LOGGING_LEVEL:INFO}

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS}
