spring:
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${OAUTH2_ISSUER_URI}

logging:
  level:
    com:
      suchorski: ${LOGGING_LEVEL:INFO}

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS}

ldap:
  enabled: ${LDAP_ENABLED:false}
  provider-url: ${LDAP_PROVIDER_URL}
  security-authentication: ${LDAP_SECURITY_AUTHENTICATION}
  security-principal: ${LDAP_SECURITY_PRINCIPAL}
  security-credentials: ${LDAP_SECURITY_CREDENTIALS}
  parameters:
    name: ${LDAP_PARAMETERS_NAME}
    nickname: ${LDAP_PARAMETERS_NICKNAME}
    rank: ${LDAP_PARAMETERS_RANK}
    company: ${LDAP_PARAMETERS_COMPANY}
  filters:
    base-ou: ${LDAP_FILTERS_BASE_OU}
    user-filter: ${LDAP_FILTERS_USER_FILTER}